project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # Frontend JSON translations
  - source: /src/locales/en.json
    translation: /src/locales/%locale_with_underscore%.json
    update_option: update_as_unapproved
    languages_mapping:
      locale_with_underscore:
        pt-PT: pt-PT
        de: de
        ko: ko
        tr: tr

  # Backend YAML translations
  # IMPORTANT: Your current locales/app.yml has all languages embedded.
  # This config assumes you'll split it into separate language files.
  # See CROWDIN_SETUP.md for migration instructions.
  # - source: /locales/en/app.yml
  #   translation: /locales/%two_letters_code%/app.yml
  #   update_option: update_as_unapproved
  #   languages_mapping:
  #     two_letters_code:
  #       pt-PT: pt-PT
  #       de: de
  #       ko: ko
  #       tr: tr
