name: Question
description: Ask about how to use FMMLoader26
title: "question: "
labels: ["Type: Question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "Describe what you need help with"
